;; The sequence of triangle numbers is generated by adding the natural numbers.
;; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
;; ten terms would be:
;; 
;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;; 
;; Let us list the factors of the first seven triangle numbers:
;; 
;;     1: 1
;;     3: 1,3
;;     6: 1,2,3,6
;;    10: 1,2,5,10
;;    15: 1,3,5,15
;;    21: 1,3,7,21
;;    28: 1,2,4,7,14,28
;;
;; We can see that 28 is the first triangle number to have over five divisors.
;;
;; What is the value of the first triangle number to have over five hundred
;; divisors?

#lang racket/base

(define (nb-divisors n)
  (let helper ([i 1]
               [sum 0]
               [max-i (quotient n 2)])
    (if (> i max-i)
      (add1 sum)
      (if (= (modulo n i) 0)
        (helper (+ 1 i) (+ 2 sum) (/ n i))
        (helper (+ 1 i) sum max-i)))))

(define (euler12 limit)
  (let helper ([c 1] [n 2])
    (if (> (nb-divisors c) limit)
      c
      (helper (+ n c) (+ 1 n)))))

(time (euler12 500))
